version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: mvn clean package
      - store_artifacts:
          path:  target
  test:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports
      - run: mvn jacoco:report
      - store_artifacts:
          path: target/site/jacoco/index.html
