version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: ./mvn clean package
      - store_artifacts:
          path:  ./target
  test:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ./mvn test
      - run: ./mvnw test verify
      - store_artifacts:
          path: target/site/jacoco/index.html
